# Generated by Django 4.2.19 on 2025-02-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=50)),
                ('screen_resolution', models.CharField(max_length=20)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('total_visits', models.IntegerField(default=1)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('last_visited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
